apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubelab-ingress
  namespace: kubelab
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: kubelab.swisscom.k8s.natron.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kubelab-service
            port:
              number: 8090
