sync:
  persistentvolumes:
    enabled: true
  storageclasses:
    enabled: false
  ingresses:
    enabled: true
  hoststorageclasses:
    enabled: true
storage:
  persistence: false
isolation:
  enabled: true
  podSecurityStandard: baseline
  nodeProxyPermission:
    enabled: false
  resourceQuota:
    enabled: false
  limitRange:
    enabled: true
    default:
      ephemeral-storage: 8Gi
      memory: 512Mi
      cpu: 1
    defaultRequest:
      ephemeral-storage: 3Gi
      memory: 128Mi
      cpu: 100m
  networkPolicy:
    enabled: true
    outgoingConnections:
      ipBlock:
        cidr: 8.8.8.8/32
        except: []
