sync:
  persistentvolumes:
    enabled: true
  storageclasses:
    enabled: false
  ingresses:
    enabled: true
  hoststorageclasses:
    enabled: true
  events:
    enabled: false
storage:
  persistence: false
isolation:
  enabled: false
  podSecurityStandard: baseline
  nodeProxyPermission:
    enabled: false
  resourceQuota:
    enabled: false
  limitRange:
    enabled: false
  networkPolicy:
    enabled: false
    outgoingConnections:
      ipBlock:
        cidr: 8.8.8.8/32
        except: []
syncer:
  kubeConfigContextName: "kubelab-vcluster"
