sync:
  persistentvolumes:
    enabled: true
  storageclasses:
    enabled: false
  ingresses:
    enabled: true
  hoststorageclasses:
    enabled: true
  events:
    enabled: false
vcluster:
  image: rancher/k3s:v1.27.7-k3s1
storage:
  persistence: false
isolation:
  enabled: true
  podSecurityStandard: privileged
  nodeProxyPermission:
    enabled: false
  resourceQuota:
    enabled: false
  limitRange:
    enabled: false
  networkPolicy:
    enabled: false
    outgoingConnections:
      ipBlock:
        cidr: 8.8.8.8/32
        except: []
syncer:
  kubeConfigContextName: "kubelab-vcluster"
