name: Size Label
on: pull_request
jobs:
  size-label:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
